# Generated by Django 5.2.3 on 2025-06-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_post',
            name='id_postagem',
            field=models.ForeignKey(db_column='id_postagem', on_delete=django.db.models.deletion.CASCADE, to='socialapp.postagem'),
        ),
    ]
