# Generated by Django 5.2.3 on 2025-06-29

from django.db import migrations, models
import django.utils.timezone


def set_default_dates(apps, schema_editor):
    Perfil = apps.get_model('socialapp', 'Perfil')
    for perfil in Perfil.objects.all():
        if not perfil.data_nascimento:
            perfil.data_nascimento = django.utils.timezone.now().date()
            perfil.save(update_fields=['data_nascimento'])


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_alter_perfil_post_id_postagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={
                'ordering': ['-data_criacao'],
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis'
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(
                blank=True,
                null=True,
                default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(
                upload_to='perfis/',
                blank=True,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='matricula_perfil',
            field=models.CharField(
                max_length=255,
                unique=True
            ),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_perfil',
            field=models.CharField(
                max_length=255,
                default='Usuário'
            ),
        ),
        migrations.RunPython(set_default_dates, migrations.RunPython.noop),
    ]
