# Generated by Django 5.2.3 on 2025-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_alter_perfil_options_perfil_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='numero_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
