# Generated by Django 5.2.3 on 2025-06-29 16:45

import socialapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_perfil_numero_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='data_postagem',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
