# Generated by Django 5.2.3 on 2025-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_migracao_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avalia',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='id_avalia',
        ),
        migrations.AlterField(
            model_name='avalia',
            name='valor_avalia',
            field=models.IntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')]),
        ),
    ]
