# Generated by Django 5.1.7 on 2025-06-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_alter_avalia_options_remove_postagem_id_avalia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_perfil',
        ),
    ]
