# Generated by Django 5.1.7 on 2025-06-30 05:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_alter_avalia_options_remove_postagem_id_avalia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Foto do Perfil'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='imagem_postagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagem da Postagem'),
        ),
    ]
