# Generated by Django 5.1.7 on 2025-06-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_alter_perfil_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='imagem_postagem',
        ),
    ]
